services:
  node:
    image: metisdao/themis:${VERSION:-dev}
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - ETH_RPC_URL=https://sepolia.infura.io/v3/6d38067be9eb4d23b27cdd5439c91a07
      - MPC_RPC_URL=tss-node:9001
      - METIS_RPC_URL=http://l2geth:8545
    volumes:
      - ./node/themis:/var/lib/themis
    ports:
      - "26656:26656" # P2P (TCP)
      - "26657:26657" # tendermint rpc (TCP)
      - "1317:1317" # rest (TCP)
    command:
      - --rest-server=true
      - start
      - --p2p.laddr=tcp://0.0.0.0:26656
      - --rpc.laddr=tcp://0.0.0.0:26657

  bridge:
    image: metisdao/themis:${VERSION:-dev}
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - LOG_LEVEL=info
      - REST_SERVER=http://node:1317
      - TENDERMINT_RPC_URL=http://node:26657
      - METIS_RPC_URL=http://l2geth:8545
      - MPC_RPC_URL=tss-node:9001
      - LOCKING_START_HEIGHT=5108808
      - IS_GAS_SENDER=true
    volumes:
      - ./node/themis:/var/lib/themis
    ports:
      - "8646:8646" # RPC (TCP)
    depends_on:
      - node
    command:
      - bridge
      - start
      - --all
      - --node=tcp://node:26657
      - --log_level=info
