name: docker-image
run-name: Build image ${{ inputs.version }}

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version"
        default: "dev"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: metisdao
          password: ${{ secrets.METIS_DOCKER_ACCESS_KEY  }}

      - name: Build
        uses: docker/build-push-action@v6
        with:
          push: true
          pull: true
          context: .
          file: Dockerfile
          tags: metisdao/themis:${{ inputs.version }}
          cache-from: type=gha,scope=buildkit-themis-${{ runner.os }}-${{ runner.arch }}
          cache-to: type=gha,mode=max,scope=buildkit-themis-${{ runner.os }}-${{ runner.arch }}
          platforms: linux/amd64
          provenance: false
          sbom: false
